pipeline {
   agent any
   stages {
       stage('Build Code') {
           steps {
               script {
               sh 'python manage.py runserver'
               }   
           }
       }
      
   }
}
